/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as LayoutTermsAndConditionRouteImport } from './routes/_layout/terms-and-condition'
import { Route as LayoutResultsRouteImport } from './routes/_layout/results'
import { Route as LayoutResponsibleGamblingRouteImport } from './routes/_layout/responsible-gambling'
import { Route as LayoutPrivacyPolicyRouteImport } from './routes/_layout/privacy-policy'
import { Route as LayoutPlayRouteImport } from './routes/_layout/play'
import { Route as LayoutHowToPlayRouteImport } from './routes/_layout/how-to-play'
import { Route as LayoutGamesRouteImport } from './routes/_layout/games'
import { Route as LayoutFaqRouteImport } from './routes/_layout/faq'
import { Route as LayoutContactRouteImport } from './routes/_layout/contact'
import { Route as LayoutAboutRouteImport } from './routes/_layout/about'
import { Route as AuthenticatedWithdrawalRouteImport } from './routes/_authenticated/withdrawal'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPayoutsRouteImport } from './routes/_authenticated/payouts'
import { Route as AuthenticatedFavouriteBallsRouteImport } from './routes/_authenticated/favourite-balls'
import { Route as AuthenticatedDepositRouteImport } from './routes/_authenticated/deposit'
import { Route as AuthenticatedSettingsVerifyEmailRouteImport } from './routes/_authenticated/settings/verify-email'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings/profile'
import { Route as AuthenticatedSettingsEmailRouteImport } from './routes/_authenticated/settings/email'
import { Route as AuthenticatedSettingsChangePasswordRouteImport } from './routes/_authenticated/settings/change-password'
import { Route as AuthenticatedSettingsBankRouteImport } from './routes/_authenticated/settings/bank'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const LayoutTermsAndConditionRoute = LayoutTermsAndConditionRouteImport.update({
  id: '/terms-and-condition',
  path: '/terms-and-condition',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutResultsRoute = LayoutResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutResponsibleGamblingRoute =
  LayoutResponsibleGamblingRouteImport.update({
    id: '/responsible-gambling',
    path: '/responsible-gambling',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutPrivacyPolicyRoute = LayoutPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPlayRoute = LayoutPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHowToPlayRoute = LayoutHowToPlayRouteImport.update({
  id: '/how-to-play',
  path: '/how-to-play',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGamesRoute = LayoutGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFaqRoute = LayoutFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutContactRoute = LayoutContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAboutRoute = LayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthenticatedWithdrawalRoute = AuthenticatedWithdrawalRouteImport.update({
  id: '/withdrawal',
  path: '/withdrawal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPayoutsRoute = AuthenticatedPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFavouriteBallsRoute =
  AuthenticatedFavouriteBallsRouteImport.update({
    id: '/favourite-balls',
    path: '/favourite-balls',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDepositRoute = AuthenticatedDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsVerifyEmailRoute =
  AuthenticatedSettingsVerifyEmailRouteImport.update({
    id: '/settings/verify-email',
    path: '/settings/verify-email',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsEmailRoute =
  AuthenticatedSettingsEmailRouteImport.update({
    id: '/settings/email',
    path: '/settings/email',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsChangePasswordRoute =
  AuthenticatedSettingsChangePasswordRouteImport.update({
    id: '/settings/change-password',
    path: '/settings/change-password',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsBankRoute =
  AuthenticatedSettingsBankRouteImport.update({
    id: '/settings/bank',
    path: '/settings/bank',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRoute
  '/auth': typeof AuthRouteWithChildren
  '/deposit': typeof AuthenticatedDepositRoute
  '/favourite-balls': typeof AuthenticatedFavouriteBallsRoute
  '/payouts': typeof AuthenticatedPayoutsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/withdrawal': typeof AuthenticatedWithdrawalRoute
  '/about': typeof LayoutAboutRoute
  '/contact': typeof LayoutContactRoute
  '/faq': typeof LayoutFaqRoute
  '/games': typeof LayoutGamesRoute
  '/how-to-play': typeof LayoutHowToPlayRoute
  '/play': typeof LayoutPlayRoute
  '/privacy-policy': typeof LayoutPrivacyPolicyRoute
  '/responsible-gambling': typeof LayoutResponsibleGamblingRoute
  '/results': typeof LayoutResultsRoute
  '/terms-and-condition': typeof LayoutTermsAndConditionRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/': typeof LayoutIndexRoute
  '/settings/bank': typeof AuthenticatedSettingsBankRoute
  '/settings/change-password': typeof AuthenticatedSettingsChangePasswordRoute
  '/settings/email': typeof AuthenticatedSettingsEmailRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/verify-email': typeof AuthenticatedSettingsVerifyEmailRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppRoute
  '/auth': typeof AuthRouteWithChildren
  '/deposit': typeof AuthenticatedDepositRoute
  '/favourite-balls': typeof AuthenticatedFavouriteBallsRoute
  '/payouts': typeof AuthenticatedPayoutsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/tickets': typeof AuthenticatedTicketsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/withdrawal': typeof AuthenticatedWithdrawalRoute
  '/about': typeof LayoutAboutRoute
  '/contact': typeof LayoutContactRoute
  '/faq': typeof LayoutFaqRoute
  '/games': typeof LayoutGamesRoute
  '/how-to-play': typeof LayoutHowToPlayRoute
  '/play': typeof LayoutPlayRoute
  '/privacy-policy': typeof LayoutPrivacyPolicyRoute
  '/responsible-gambling': typeof LayoutResponsibleGamblingRoute
  '/results': typeof LayoutResultsRoute
  '/terms-and-condition': typeof LayoutTermsAndConditionRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/': typeof LayoutIndexRoute
  '/settings/bank': typeof AuthenticatedSettingsBankRoute
  '/settings/change-password': typeof AuthenticatedSettingsChangePasswordRoute
  '/settings/email': typeof AuthenticatedSettingsEmailRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/verify-email': typeof AuthenticatedSettingsVerifyEmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/app': typeof AppRoute
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/deposit': typeof AuthenticatedDepositRoute
  '/_authenticated/favourite-balls': typeof AuthenticatedFavouriteBallsRoute
  '/_authenticated/payouts': typeof AuthenticatedPayoutsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/tickets': typeof AuthenticatedTicketsRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/withdrawal': typeof AuthenticatedWithdrawalRoute
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/contact': typeof LayoutContactRoute
  '/_layout/faq': typeof LayoutFaqRoute
  '/_layout/games': typeof LayoutGamesRoute
  '/_layout/how-to-play': typeof LayoutHowToPlayRoute
  '/_layout/play': typeof LayoutPlayRoute
  '/_layout/privacy-policy': typeof LayoutPrivacyPolicyRoute
  '/_layout/responsible-gambling': typeof LayoutResponsibleGamblingRoute
  '/_layout/results': typeof LayoutResultsRoute
  '/_layout/terms-and-condition': typeof LayoutTermsAndConditionRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_authenticated/settings/bank': typeof AuthenticatedSettingsBankRoute
  '/_authenticated/settings/change-password': typeof AuthenticatedSettingsChangePasswordRoute
  '/_authenticated/settings/email': typeof AuthenticatedSettingsEmailRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/settings/verify-email': typeof AuthenticatedSettingsVerifyEmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/auth'
    | '/deposit'
    | '/favourite-balls'
    | '/payouts'
    | '/profile'
    | '/tickets'
    | '/transactions'
    | '/wallet'
    | '/withdrawal'
    | '/about'
    | '/contact'
    | '/faq'
    | '/games'
    | '/how-to-play'
    | '/play'
    | '/privacy-policy'
    | '/responsible-gambling'
    | '/results'
    | '/terms-and-condition'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/'
    | '/settings/bank'
    | '/settings/change-password'
    | '/settings/email'
    | '/settings/profile'
    | '/settings/verify-email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app'
    | '/auth'
    | '/deposit'
    | '/favourite-balls'
    | '/payouts'
    | '/profile'
    | '/tickets'
    | '/transactions'
    | '/wallet'
    | '/withdrawal'
    | '/about'
    | '/contact'
    | '/faq'
    | '/games'
    | '/how-to-play'
    | '/play'
    | '/privacy-policy'
    | '/responsible-gambling'
    | '/results'
    | '/terms-and-condition'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/'
    | '/settings/bank'
    | '/settings/change-password'
    | '/settings/email'
    | '/settings/profile'
    | '/settings/verify-email'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_layout'
    | '/app'
    | '/auth'
    | '/_authenticated/deposit'
    | '/_authenticated/favourite-balls'
    | '/_authenticated/payouts'
    | '/_authenticated/profile'
    | '/_authenticated/tickets'
    | '/_authenticated/transactions'
    | '/_authenticated/wallet'
    | '/_authenticated/withdrawal'
    | '/_layout/about'
    | '/_layout/contact'
    | '/_layout/faq'
    | '/_layout/games'
    | '/_layout/how-to-play'
    | '/_layout/play'
    | '/_layout/privacy-policy'
    | '/_layout/responsible-gambling'
    | '/_layout/results'
    | '/_layout/terms-and-condition'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/signup'
    | '/_layout/'
    | '/_authenticated/settings/bank'
    | '/_authenticated/settings/change-password'
    | '/_authenticated/settings/email'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/verify-email'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_layout/terms-and-condition': {
      id: '/_layout/terms-and-condition'
      path: '/terms-and-condition'
      fullPath: '/terms-and-condition'
      preLoaderRoute: typeof LayoutTermsAndConditionRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/results': {
      id: '/_layout/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof LayoutResultsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/responsible-gambling': {
      id: '/_layout/responsible-gambling'
      path: '/responsible-gambling'
      fullPath: '/responsible-gambling'
      preLoaderRoute: typeof LayoutResponsibleGamblingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/privacy-policy': {
      id: '/_layout/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof LayoutPrivacyPolicyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/play': {
      id: '/_layout/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof LayoutPlayRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/how-to-play': {
      id: '/_layout/how-to-play'
      path: '/how-to-play'
      fullPath: '/how-to-play'
      preLoaderRoute: typeof LayoutHowToPlayRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/games': {
      id: '/_layout/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof LayoutGamesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/faq': {
      id: '/_layout/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof LayoutFaqRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/contact': {
      id: '/_layout/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof LayoutContactRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_authenticated/withdrawal': {
      id: '/_authenticated/withdrawal'
      path: '/withdrawal'
      fullPath: '/withdrawal'
      preLoaderRoute: typeof AuthenticatedWithdrawalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payouts': {
      id: '/_authenticated/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof AuthenticatedPayoutsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/favourite-balls': {
      id: '/_authenticated/favourite-balls'
      path: '/favourite-balls'
      fullPath: '/favourite-balls'
      preLoaderRoute: typeof AuthenticatedFavouriteBallsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deposit': {
      id: '/_authenticated/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof AuthenticatedDepositRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/verify-email': {
      id: '/_authenticated/settings/verify-email'
      path: '/settings/verify-email'
      fullPath: '/settings/verify-email'
      preLoaderRoute: typeof AuthenticatedSettingsVerifyEmailRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/email': {
      id: '/_authenticated/settings/email'
      path: '/settings/email'
      fullPath: '/settings/email'
      preLoaderRoute: typeof AuthenticatedSettingsEmailRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/change-password': {
      id: '/_authenticated/settings/change-password'
      path: '/settings/change-password'
      fullPath: '/settings/change-password'
      preLoaderRoute: typeof AuthenticatedSettingsChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/bank': {
      id: '/_authenticated/settings/bank'
      path: '/settings/bank'
      fullPath: '/settings/bank'
      preLoaderRoute: typeof AuthenticatedSettingsBankRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDepositRoute: typeof AuthenticatedDepositRoute
  AuthenticatedFavouriteBallsRoute: typeof AuthenticatedFavouriteBallsRoute
  AuthenticatedPayoutsRoute: typeof AuthenticatedPayoutsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedWithdrawalRoute: typeof AuthenticatedWithdrawalRoute
  AuthenticatedSettingsBankRoute: typeof AuthenticatedSettingsBankRoute
  AuthenticatedSettingsChangePasswordRoute: typeof AuthenticatedSettingsChangePasswordRoute
  AuthenticatedSettingsEmailRoute: typeof AuthenticatedSettingsEmailRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsVerifyEmailRoute: typeof AuthenticatedSettingsVerifyEmailRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDepositRoute: AuthenticatedDepositRoute,
  AuthenticatedFavouriteBallsRoute: AuthenticatedFavouriteBallsRoute,
  AuthenticatedPayoutsRoute: AuthenticatedPayoutsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedWithdrawalRoute: AuthenticatedWithdrawalRoute,
  AuthenticatedSettingsBankRoute: AuthenticatedSettingsBankRoute,
  AuthenticatedSettingsChangePasswordRoute:
    AuthenticatedSettingsChangePasswordRoute,
  AuthenticatedSettingsEmailRoute: AuthenticatedSettingsEmailRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsVerifyEmailRoute: AuthenticatedSettingsVerifyEmailRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutContactRoute: typeof LayoutContactRoute
  LayoutFaqRoute: typeof LayoutFaqRoute
  LayoutGamesRoute: typeof LayoutGamesRoute
  LayoutHowToPlayRoute: typeof LayoutHowToPlayRoute
  LayoutPlayRoute: typeof LayoutPlayRoute
  LayoutPrivacyPolicyRoute: typeof LayoutPrivacyPolicyRoute
  LayoutResponsibleGamblingRoute: typeof LayoutResponsibleGamblingRoute
  LayoutResultsRoute: typeof LayoutResultsRoute
  LayoutTermsAndConditionRoute: typeof LayoutTermsAndConditionRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutContactRoute: LayoutContactRoute,
  LayoutFaqRoute: LayoutFaqRoute,
  LayoutGamesRoute: LayoutGamesRoute,
  LayoutHowToPlayRoute: LayoutHowToPlayRoute,
  LayoutPlayRoute: LayoutPlayRoute,
  LayoutPrivacyPolicyRoute: LayoutPrivacyPolicyRoute,
  LayoutResponsibleGamblingRoute: LayoutResponsibleGamblingRoute,
  LayoutResultsRoute: LayoutResultsRoute,
  LayoutTermsAndConditionRoute: LayoutTermsAndConditionRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
  AppRoute: AppRoute,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
